### ISSUE TITLE
[BUG] Write the correct lane_index and bundling

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/geo_to_hca#12]
**Description of the issue**:
The use of the HCA for lane_index is none other than being able to distinguish files within a bundle that should be analysed together (e.g. R1 and R2 of a run). Up until now, the lane index has been filled based on filename, but this might not be a valid value in some scenarios (e.g. GSE135893). 

While in the process of investigating this, another issue arose: For the same dataset, the converter created 228 different bundles, but the experiment consists of only 34 experiment accessions.

**Expected behaviour**:
- Creates a single bundle per experiment accession
- Lane indexes are assigned incrementally based on number of runs in a experiment.

**Current behaviour**:
- Not really sure how the current script creates bundles
- Lane indexes are filled using the filename

**Effort/Value**:
Low/Medium - This issue is not a blocker but takes time from the wrangling process. Correcting it should only take a couple lines of code.

**Comment by ami-day** [comment]
1. Create a single bundle per experiment accession - DONE. Process_id is now the experiment accession.

2. Up until now, the lane index has been filled based on filename using a regex (re.findall('L[0-9]{3}', filename)[0][-1] or re.findall('L[0-9]{4}', filename)[0][-1]). In some cases this might not be a valid value (e.g. GSE135893)'. I decided to keep this feature, and in cases where a regex is not valid, an empty value is added in the lane index field. Since in most cases regex is valid, it shouldn't be an issue to fill the index values manually in the rarer cases. I am hesitant to add artificial lane indexes by assigning them incrementally based on the number of runs in an experiment in case of confusion.
